// <copyright file="Achievements.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using System.Collections.Generic;
    using Internal;

    /// <summary>
    /// Provides access to achievements registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class Achievements
    {
        private static readonly UnifiedAchievement s_firstship = new UnifiedAchievement("Firstship",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIuM6xmOUFEAIQBA"
#else
            "Firstship"
#endif
            );

        public static UnifiedAchievement Firstship
        {
            get { return s_firstship; }
        }

        private static readonly UnifiedAchievement s_secondship = new UnifiedAchievement("Secondship",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIuM6xmOUFEAIQBQ"
#else
            "Secondship"
#endif
            );

        public static UnifiedAchievement Secondship
        {
            get { return s_secondship; }
        }

        private static readonly UnifiedAchievement s_thirdship = new UnifiedAchievement("Thirdship",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIuM6xmOUFEAIQBg"
#else
            "Thirdship"
#endif
            );

        public static UnifiedAchievement Thirdship
        {
            get { return s_thirdship; }
        }

        private static readonly UnifiedAchievement s_kill10enemys = new UnifiedAchievement("Kill10enemys",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIuM6xmOUFEAIQCQ"
#else
            "Kill10enemys"
#endif
            );

        public static UnifiedAchievement Kill10enemys
        {
            get { return s_kill10enemys; }
        }

        private static readonly UnifiedAchievement s_kill50enemys = new UnifiedAchievement("Kill50enemys",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIuM6xmOUFEAIQCg"
#else
            "Kill50enemys"
#endif
            );

        public static UnifiedAchievement Kill50enemys
        {
            get { return s_kill50enemys; }
        }

        private static readonly UnifiedAchievement s_kill100enemys = new UnifiedAchievement("Kill100enemys",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIuM6xmOUFEAIQCw"
#else
            "Kill100enemys"
#endif
            );

        public static UnifiedAchievement Kill100enemys
        {
            get { return s_kill100enemys; }
        }

        private static readonly UnifiedAchievement s_benefactor = new UnifiedAchievement("Benefactor",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIuM6xmOUFEAIQAQ"
#else
            "Benefactor"
#endif
            );

        public static UnifiedAchievement Benefactor
        {
            get { return s_benefactor; }
        }

        private static readonly UnifiedAchievement s_get20000coins = new UnifiedAchievement("Get20000coins",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIuM6xmOUFEAIQAg"
#else
            "Get20000coins"
#endif
            );

        public static UnifiedAchievement Get20000coins
        {
            get { return s_get20000coins; }
        }

        private static readonly UnifiedAchievement s_noAds = new UnifiedAchievement("NoAds",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIuM6xmOUFEAIQAw"
#else
            "NoAds"
#endif
            );

        public static UnifiedAchievement NoAds
        {
            get { return s_noAds; }
        }

        private static readonly UnifiedAchievement s_kill200enemys = new UnifiedAchievement("Kill200enemys",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIuM6xmOUFEAIQDQ"
#else
            "Kill200enemys"
#endif
            );

        public static UnifiedAchievement Kill200enemys
        {
            get { return s_kill200enemys; }
        }

        private static readonly UnifiedAchievement s_kill500enemys = new UnifiedAchievement("Kill500enemys",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIuM6xmOUFEAIQDg"
#else
            "Kill500enemys"
#endif
            );

        public static UnifiedAchievement Kill500enemys
        {
            get { return s_kill500enemys; }
        }

        private static readonly UnifiedAchievement s_kill1000enemys = new UnifiedAchievement("Kill1000enemys",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIuM6xmOUFEAIQDw"
#else
            "Kill1000enemys"
#endif
            );

        public static UnifiedAchievement Kill1000enemys
        {
            get { return s_kill1000enemys; }
        }

        private static readonly UnifiedAchievement s_firstgame = new UnifiedAchievement("Firstgame",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIuM6xmOUFEAIQEA"
#else
            "Firstgame"
#endif
            );

        public static UnifiedAchievement Firstgame
        {
            get { return s_firstgame; }
        }

        private static readonly UnifiedAchievement s_firstdeath = new UnifiedAchievement("Firstdeath",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIuM6xmOUFEAIQEQ"
#else
            "Firstdeath"
#endif
            );

        public static UnifiedAchievement Firstdeath
        {
            get { return s_firstdeath; }
        }

        private static readonly UnifiedAchievement s_games10 = new UnifiedAchievement("games10",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIuM6xmOUFEAIQEg"
#else
            "games10"
#endif
            );

        public static UnifiedAchievement games10
        {
            get { return s_games10; }
        }

        private static readonly UnifiedAchievement s_games100 = new UnifiedAchievement("games100",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIuM6xmOUFEAIQEw"
#else
            "games100"
#endif
            );

        public static UnifiedAchievement games100
        {
            get { return s_games100; }
        }

        private static readonly UnifiedAchievement s_games150 = new UnifiedAchievement("games150",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIuM6xmOUFEAIQFA"
#else
            "games150"
#endif
            );

        public static UnifiedAchievement games150
        {
            get { return s_games150; }
        }

        private static readonly UnifiedAchievement s_games500 = new UnifiedAchievement("games500",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkIuM6xmOUFEAIQFQ"
#else
            "games500"
#endif
            );

        public static UnifiedAchievement games500
        {
            get { return s_games500; }
        }

        public static readonly UnifiedAchievement[] All =
        {
            s_firstship,
            s_secondship,
            s_thirdship,
            s_kill10enemys,
            s_kill50enemys,
            s_kill100enemys,
            s_benefactor,
            s_get20000coins,
            s_noAds,
            s_kill200enemys,
            s_kill500enemys,
            s_kill1000enemys,
            s_firstgame,
            s_firstdeath,
            s_games10,
            s_games100,
            s_games150,
            s_games500,
        };

        public static string GetPlatformID(string internalId)
        {
            return s_achievementDictionary.ContainsKey(internalId)
                ? s_achievementDictionary[internalId].ID
                : string.Empty;
        }

        private static readonly Dictionary<string, UnifiedAchievement> s_achievementDictionary = new Dictionary<string, UnifiedAchievement>
        {
            { "Firstship", s_firstship },
            { "Secondship", s_secondship },
            { "Thirdship", s_thirdship },
            { "Kill10enemys", s_kill10enemys },
            { "Kill50enemys", s_kill50enemys },
            { "Kill100enemys", s_kill100enemys },
            { "Benefactor", s_benefactor },
            { "Get20000coins", s_get20000coins },
            { "NoAds", s_noAds },
            { "Kill200enemys", s_kill200enemys },
            { "Kill500enemys", s_kill500enemys },
            { "Kill1000enemys", s_kill1000enemys },
            { "Firstgame", s_firstgame },
            { "Firstdeath", s_firstdeath },
            { "games10", s_games10 },
            { "games100", s_games100 },
            { "games150", s_games150 },
            { "games500", s_games500 },
        };
    }
}
