// <copyright file="CloudIDs.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
#if (UNITY_ANDROID || UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
    using Internal;
    using UnityEngine;
#endif
    /// <summary>
    /// Provides access to achievement- and leaderboard IDs registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class CloudIDs
    {
        /// <summary>
        /// Contains properties that retrieves achievement IDs for the current platform.
        /// </summary>
        public static class AchievementIDs
        {
            public static string Firstship
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIuM6xmOUFEAIQBA";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "Firstship";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Secondship
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIuM6xmOUFEAIQBQ";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "Secondship";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Thirdship
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIuM6xmOUFEAIQBg";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "Thirdship";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Kill10enemys
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIuM6xmOUFEAIQCQ";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "Kill10enemys";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Kill50enemys
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIuM6xmOUFEAIQCg";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "Kill50enemys";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Kill100enemys
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIuM6xmOUFEAIQCw";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "Kill100enemys";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Benefactor
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIuM6xmOUFEAIQAQ";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "Benefactor";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Get20000coins
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIuM6xmOUFEAIQAg";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "Get20000coins";
#else
                    return string.Empty;
#endif
                }
            }

            public static string NoAds
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIuM6xmOUFEAIQAw";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "NoAds";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Kill200enemys
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIuM6xmOUFEAIQDQ";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "Kill200enemys";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Kill500enemys
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIuM6xmOUFEAIQDg";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "Kill500enemys";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Kill1000enemys
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIuM6xmOUFEAIQDw";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "Kill1000enemys";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Firstgame
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIuM6xmOUFEAIQEA";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "Firstgame";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Firstdeath
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIuM6xmOUFEAIQEQ";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "Firstdeath";
#else
                    return string.Empty;
#endif
                }
            }

            public static string games10
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIuM6xmOUFEAIQEg";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "games10";
#else
                    return string.Empty;
#endif
                }
            }

            public static string games100
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIuM6xmOUFEAIQEw";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "games100";
#else
                    return string.Empty;
#endif
                }
            }

            public static string games150
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIuM6xmOUFEAIQFA";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "games150";
#else
                    return string.Empty;
#endif
                }
            }

            public static string games500
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIuM6xmOUFEAIQFQ";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "games500";
#else
                    return string.Empty;
#endif
                }
            }
        }

        /// <summary>
        /// Contains properties that retrieves leaderboard IDs for the current platform.
        /// </summary>
        public static class LeaderboardIDs
        {
            public static string Richestman
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIuM6xmOUFEAIQBw";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "Richestman";
#else
                    return string.Empty;
#endif
                }
            }

            public static string HightScore
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if CLOUDONCE_GOOGLE
                    return "CgkIuM6xmOUFEAIQCA";
#else
                    return string.Empty;
#endif
#elif (UNITY_IOS || UNITY_TVOS) && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "HightScore";
#else
                    return string.Empty;
#endif
                }
            }
        }
    }
}
